name: uni-app 定时任务

on:
	workflow_dispatch:
    schedule:
        - cron: "*/5 8-16 * * *" # 服务器是UTC时间，实则凌晨0-8点执行

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd scripts/uni-crontab/ && npm ci
    - run: cd scripts/uni-crontab/ && node scripts/crontab.js
		env:
	    APP_KEY: ${{ secrets.UNI_CRON_APP_KEY }}
    #- run: npm run build --if-present
    #- run: npm test
